### PR TITLE
fix: Disable UpdateLastConnected in toml file

### LINKED ISSUE #40: Failed to update last connected value for device
level=ERROR ts=2021-06-24T17:31:16.245465281Z app=edgex-device-rfid-llrp source=utils.go:302 msg="Failed to update last connected value for device: SpeedwayR-10-EF-18"

### PR DESCRIPTION
**Pull request by ajcasagrande**
Signed-off-by: Anthony Casagrande anthony.j.casagrande@intel.com

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue Number:
Closes #40 

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## New Imports

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
recheck

**Comment by lenny-intel** [comment]
recheck

**Comment by ajcasagrande** [comment]
recheck

**Pull request merged**
